//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoContactSheetMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoContactSheetMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] absender1 {
            get {
                object obj = ResourceManager.GetObject("absender1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg timeout. File: {0}.
        /// </summary>
        internal static string FFMpegTimeoutFile {
            get {
                return ResourceManager.GetString("FFMpegTimeoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFprobe error: {0}, File: {1}.
        /// </summary>
        internal static string FFprobeError {
            get {
                return ResourceManager.GetString("FFprobeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFProbe process exceeded execution timeout ({0}) and was aborted, File: {1}.
        /// </summary>
        internal static string FFProbeProcessExceededExecutionTimeout {
            get {
                return ResourceManager.GetString("FFProbeProcessExceededExecutionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FUTRFW {
            get {
                object obj = ResourceManager.GetObject("FUTRFW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required: Include a file or folder.
        /// </summary>
        internal static string IncludeAFileOrFolder {
            get {
                return ResourceManager.GetString("IncludeAFileOrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: {0}.
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing arguments.
        /// </summary>
        internal static string MissingArgs {
            get {
                return ResourceManager.GetString("MissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing {0} file.
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing include argument.
        /// </summary>
        internal static string MissingIncludeArgument {
            get {
                return ResourceManager.GetString("MissingIncludeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input file / folder.
        /// </summary>
        internal static string MissingInputFileFolder {
            get {
                return ResourceManager.GetString("MissingInputFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing output folder argument.
        /// </summary>
        internal static string MissingOutputFolderArgument {
            get {
                return ResourceManager.GetString("MissingOutputFolderArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monofonto {
            get {
                object obj = ResourceManager.GetObject("monofonto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] neoletters {
            get {
                object obj = ResourceManager.GetObject("neoletters", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Output folder, by default its the same folder as the file.
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Path to profile or a default profile name, otherwise it uses standard profile.
        /// </summary>
        internal static string ProfilePath {
            get {
                return ResourceManager.GetString("ProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Recursive, applies to included folders.
        /// </summary>
        internal static string RecursiveAppliesToIncludedFolders {
            get {
                return ResourceManager.GetString("RecursiveAppliesToIncludedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RobotoMono_Bold {
            get {
                object obj = ResourceManager.GetObject("RobotoMono_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; does not exist!.
        /// </summary>
        internal static string ThePathDoesNotExist {
            get {
                return ResourceManager.GetString("ThePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile path is invalid.
        /// </summary>
        internal static string TheProfilePathIsInvalid {
            get {
                return ResourceManager.GetString("TheProfilePathIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument {0}.
        /// </summary>
        internal static string UnknownArgument {
            get {
                return ResourceManager.GetString("UnknownArgument", resourceCulture);
            }
        }
    }
}
